version: "3"
services:
  web-flask:
    build: .
    container_name: 'themandalorian'
    command: sh -c 'python app.py'
    ports:
      - '5000:5000'
    volumes:
      - ./api:/api
    depends_on:
      - "db-mandalorian"

  db-mandalorian:
    container_name: 'db-mandalorian'
    image: redis
    ports:
      - "6379:6379"